version: '3'

services: 
  java:
    container_name: 'tesseract'
    build: .
    volumes: 
      - ./target/img-ocr-1.0.jar:/home/jar/img-ocr-1.0.jar
    command: "java -jar /home/jar/img-ocr-1.0.jar"
    ports:
      - 8181:8080
    environment:
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata/